<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\User;
use App\Models\Shelf;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::first();
        $shelves = Shelf::all()->keyBy('id');

        $books = [
            // Currently Reading
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'isbn' => '978-0735211292',
                'genre' => 'Self-Help',
                'language' => 'English',
                'publisher' => 'Avery',
                'publish_year' => 2018,
                'pages' => 320,
                'format' => 'hardcover',
                'spine_color_light' => '#2C5F2D',
                'spine_color_medium' => '#3A7B3E',
                'spine_color_dark' => '#4A8B4F',
                'height' => 'medium',
                'thickness' => 'regular',
                'status' => 'reading',
                'favorite' => false,
                'current_page' => 156,
                'progress' => 48.75,
                'started_date' => '2024-05-15 10:00:00',
                'shelf_id' => $shelves->first()->id,
                'position' => 0,
                'date_added' => '2024-05-01 00:00:00',
                'last_modified' => '2024-06-27 06:00:00',
                'purchase_date' => '2024-04-20 00:00:00',
                'purchase_price' => 24.99,
                'purchase_location' => 'Amazon',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'isbn' => '978-0441172719',
                'genre' => 'Science Fiction',
                'language' => 'English',
                'publisher' => 'Ace',
                'publish_year' => 1965,
                'pages' => 896,
                'format' => 'paperback',
                'spine_color_light' => '#C4A35A',
                'spine_color_medium' => '#8B7355',
                'spine_color_dark' => '#D4A574',
                'height' => 'tall',
                'thickness' => 'thick',
                'status' => 'reading',
                'favorite' => true,
                'current_page' => 234,
                'progress' => 26.11,
                'started_date' => '2024-06-01 14:30:00',
                'shelf_id' => $shelves->first()->id,
                'position' => 1,
                'date_added' => '2024-05-15 00:00:00',
                'last_modified' => '2024-06-27 06:00:00',
                'purchase_date' => '2024-05-10 00:00:00',
                'purchase_price' => 18.99,
                'purchase_location' => 'Bookstore',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'The Psychology of Money',
                'author' => 'Morgan Housel',
                'isbn' => '978-0857197689',
                'genre' => 'Finance',
                'language' => 'English',
                'publisher' => 'Harriman House',
                'publish_year' => 2020,
                'pages' => 256,
                'format' => 'ebook',
                'spine_color_light' => '#1E40AF',
                'spine_color_medium' => '#2563EB',
                'spine_color_dark' => '#3B82F6',
                'height' => 'short',
                'thickness' => 'thin',
                'status' => 'reading',
                'favorite' => false,
                'current_page' => 89,
                'progress' => 34.77,
                'started_date' => '2024-06-10 09:00:00',
                'shelf_id' => $shelves->first()->id,
                'position' => 2,
                'date_added' => '2024-06-01 00:00:00',
                'last_modified' => '2024-06-27 06:00:00',
                'purchase_date' => '2024-05-25 00:00:00',
                'purchase_price' => 14.99,
                'purchase_location' => 'Kindle Store',
            ],
            // Finished - Favorites
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => '1984',
                'author' => 'George Orwell',
                'isbn' => '978-0451524935',
                'genre' => 'Dystopian',
                'language' => 'English',
                'publisher' => 'Signet Classic',
                'publish_year' => 1950,
                'pages' => 328,
                'format' => 'paperback',
                'spine_color_light' => '#1F2937',
                'spine_color_medium' => '#374151',
                'spine_color_dark' => '#4B5563',
                'height' => 'medium',
                'thickness' => 'regular',
                'status' => 'finished',
                'favorite' => true,
                'progress' => 100.00,
                'started_date' => '2024-03-01 00:00:00',
                'finished_date' => '2024-04-20 00:00:00',
                'shelf_id' => $shelves->first()->id,
                'position' => 3,
                'date_added' => '2024-02-20 00:00:00',
                'last_modified' => '2024-04-20 00:00:00',
                'purchase_date' => '2024-02-15 00:00:00',
                'purchase_price' => 12.99,
                'purchase_location' => 'Bookstore',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '978-0061120084',
                'genre' => 'Classic',
                'language' => 'English',
                'publisher' => 'Harper Perennial',
                'publish_year' => 2006,
                'pages' => 336,
                'format' => 'paperback',
                'spine_color_light' => '#7C2D12',
                'spine_color_medium' => '#9A3412',
                'spine_color_dark' => '#C2410C',
                'height' => 'tall',
                'thickness' => 'regular',
                'status' => 'finished',
                'favorite' => true,
                'progress' => 100.00,
                'started_date' => '2024-02-01 00:00:00',
                'finished_date' => '2024-03-15 00:00:00',
                'shelf_id' => $shelves->first()->id,
                'position' => 4,
                'date_added' => '2024-01-20 00:00:00',
                'last_modified' => '2024-03-15 00:00:00',
                'purchase_date' => '2024-01-15 00:00:00',
                'purchase_price' => 15.99,
                'purchase_location' => 'Amazon',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'isbn' => '978-0743273565',
                'genre' => 'Classic',
                'language' => 'English',
                'publisher' => 'Scribner',
                'publish_year' => 2004,
                'pages' => 180,
                'format' => 'hardcover',
                'spine_color_light' => '#1E3A5F',
                'spine_color_medium' => '#2E5077',
                'spine_color_dark' => '#3E6B8F',
                'height' => 'short',
                'thickness' => 'thin',
                'status' => 'finished',
                'favorite' => true,
                'progress' => 100.00,
                'started_date' => '2024-01-15 00:00:00',
                'finished_date' => '2024-02-28 00:00:00',
                'shelf_id' => $shelves->first()->id,
                'position' => 5,
                'date_added' => '2024-01-10 00:00:00',
                'last_modified' => '2024-02-28 00:00:00',
                'purchase_date' => '2024-01-05 00:00:00',
                'purchase_price' => 19.99,
                'purchase_location' => 'Bookstore',
            ],
            // Finished - Regular
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Sapiens',
                'author' => 'Yuval Noah Harari',
                'isbn' => '978-0062316097',
                'genre' => 'History',
                'language' => 'English',
                'publisher' => 'Harper',
                'publish_year' => 2015,
                'pages' => 443,
                'format' => 'hardcover',
                'spine_color_light' => '#B45309',
                'spine_color_medium' => '#D97706',
                'spine_color_dark' => '#F59E0B',
                'height' => 'tall',
                'thickness' => 'thick',
                'status' => 'finished',
                'favorite' => false,
                'progress' => 100.00,
                'started_date' => '2023-11-01 00:00:00',
                'finished_date' => '2024-01-10 00:00:00',
                'shelf_id' => $shelves->slice(1, 1)->first()->id,
                'position' => 0,
                'date_added' => '2023-10-20 00:00:00',
                'last_modified' => '2024-01-10 00:00:00',
                'purchase_date' => '2023-10-15 00:00:00',
                'purchase_price' => 28.99,
                'purchase_location' => 'Amazon',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'isbn' => '978-0374533557',
                'genre' => 'Psychology',
                'language' => 'English',
                'publisher' => 'Farrar, Straus and Giroux',
                'publish_year' => 2013,
                'pages' => 499,
                'format' => 'paperback',
                'spine_color_light' => '#581C87',
                'spine_color_medium' => '#7C3AED',
                'spine_color_dark' => '#8B5CF6',
                'height' => 'medium',
                'thickness' => 'regular',
                'status' => 'finished',
                'favorite' => false,
                'progress' => 100.00,
                'started_date' => '2023-10-01 00:00:00',
                'finished_date' => '2023-12-05 00:00:00',
                'shelf_id' => $shelves->slice(1, 1)->first()->id,
                'position' => 1,
                'date_added' => '2023-09-25 00:00:00',
                'last_modified' => '2023-12-05 00:00:00',
                'purchase_date' => '2023-09-20 00:00:00',
                'purchase_price' => 17.99,
                'purchase_location' => 'Bookstore',
            ],
            // Unread
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Project Hail Mary',
                'author' => 'Andy Weir',
                'isbn' => '978-0593135204',
                'genre' => 'Science Fiction',
                'language' => 'English',
                'publisher' => 'Ballantine Books',
                'publish_year' => 2021,
                'pages' => 476,
                'format' => 'hardcover',
                'spine_color_light' => '#0369A1',
                'spine_color_medium' => '#0EA5E9',
                'spine_color_dark' => '#38BDF8',
                'height' => 'tall',
                'thickness' => 'regular',
                'status' => 'unread',
                'favorite' => false,
                'shelf_id' => $shelves->slice(1, 1)->first()->id,
                'position' => 2,
                'date_added' => '2024-05-20 00:00:00',
                'last_modified' => '2024-05-20 00:00:00',
                'purchase_date' => '2024-05-15 00:00:00',
                'purchase_price' => 28.99,
                'purchase_location' => 'Amazon',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'The Midnight Library',
                'author' => 'Matt Haig',
                'isbn' => '978-0525559474',
                'genre' => 'Fiction',
                'language' => 'English',
                'publisher' => 'Viking',
                'publish_year' => 2020,
                'pages' => 304,
                'format' => 'paperback',
                'spine_color_light' => '#7E22CE',
                'spine_color_medium' => '#A855F7',
                'spine_color_dark' => '#C084FC',
                'height' => 'short',
                'thickness' => 'thin',
                'status' => 'unread',
                'favorite' => false,
                'shelf_id' => $shelves->slice(1, 1)->first()->id,
                'position' => 3,
                'date_added' => '2024-05-25 00:00:00',
                'last_modified' => '2024-05-25 00:00:00',
                'purchase_date' => '2024-05-20 00:00:00',
                'purchase_price' => 16.99,
                'purchase_location' => 'Bookstore',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Educated',
                'author' => 'Tara Westover',
                'isbn' => '978-0399590504',
                'genre' => 'Memoir',
                'language' => 'English',
                'publisher' => 'Random House',
                'publish_year' => 2018,
                'pages' => 352,
                'format' => 'paperback',
                'spine_color_light' => '#047857',
                'spine_color_medium' => '#10B981',
                'spine_color_dark' => '#34D399',
                'height' => 'medium',
                'thickness' => 'regular',
                'status' => 'unread',
                'favorite' => false,
                'shelf_id' => $shelves->slice(1, 1)->first()->id,
                'position' => 4,
                'date_added' => '2024-06-01 00:00:00',
                'last_modified' => '2024-06-01 00:00:00',
                'purchase_date' => '2024-05-28 00:00:00',
                'purchase_price' => 17.99,
                'purchase_location' => 'Amazon',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'isbn' => '978-0062315007',
                'genre' => 'Fiction',
                'language' => 'English',
                'publisher' => 'HarperOne',
                'publish_year' => 2014,
                'pages' => 208,
                'format' => 'paperback',
                'spine_color_light' => '#B91C1C',
                'spine_color_medium' => '#EF4444',
                'spine_color_dark' => '#F87171',
                'height' => 'short',
                'thickness' => 'thin',
                'status' => 'unread',
                'favorite' => false,
                'shelf_id' => $shelves->slice(1, 1)->first()->id,
                'position' => 5,
                'date_added' => '2024-06-05 00:00:00',
                'last_modified' => '2024-06-05 00:00:00',
                'purchase_date' => '2024-06-01 00:00:00',
                'purchase_price' => 14.99,
                'purchase_location' => 'Bookstore',
            ],
            // Borrowed Out
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'The Subtle Art of Not Giving a F*ck',
                'author' => 'Mark Manson',
                'isbn' => '978-0062457714',
                'genre' => 'Self-Help',
                'language' => 'English',
                'publisher' => 'HarperOne',
                'publish_year' => 2016,
                'pages' => 224,
                'format' => 'paperback',
                'spine_color_light' => '#DC2626',
                'spine_color_medium' => '#F87171',
                'spine_color_dark' => '#EF4444',
                'height' => 'medium',
                'thickness' => 'regular',
                'status' => 'borrowed',
                'favorite' => false,
                'borrowed_by' => 'John',
                'borrowed_date' => '2024-06-01 00:00:00',
                'due_date' => '2024-07-01 00:00:00',
                'is_returned' => false,
                'shelf_id' => $shelves->slice(1, 1)->first()->id,
                'position' => 6,
                'date_added' => '2024-05-10 00:00:00',
                'last_modified' => '2024-06-01 00:00:00',
                'purchase_date' => '2024-05-05 00:00:00',
                'purchase_price' => 16.99,
                'purchase_location' => 'Amazon',
            ],
            // More finished books
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Rich Dad Poor Dad',
                'author' => 'Robert Kiyosaki',
                'isbn' => '978-1612680194',
                'genre' => 'Finance',
                'language' => 'English',
                'publisher' => 'Plata Publishing',
                'publish_year' => 2017,
                'pages' => 336,
                'format' => 'paperback',
                'spine_color_light' => '#92400E',
                'spine_color_medium' => '#B45309',
                'spine_color_dark' => '#D97706',
                'height' => 'medium',
                'thickness' => 'regular',
                'status' => 'finished',
                'favorite' => false,
                'progress' => 100.00,
                'started_date' => '2023-10-15 00:00:00',
                'finished_date' => '2023-11-20 00:00:00',
                'shelf_id' => $shelves->slice(2, 1)->first()->id,
                'position' => 0,
                'date_added' => '2023-10-05 00:00:00',
                'last_modified' => '2023-11-20 00:00:00',
                'purchase_date' => '2023-10-01 00:00:00',
                'purchase_price' => 18.99,
                'purchase_location' => 'Bookstore',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'The Four Hour Work Week',
                'author' => 'Tim Ferriss',
                'isbn' => '978-0307465131',
                'genre' => 'Business',
                'language' => 'English',
                'publisher' => 'Crown Currency',
                'publish_year' => 2009,
                'pages' => 416,
                'format' => 'paperback',
                'spine_color_light' => '#065F46',
                'spine_color_medium' => '#10B981',
                'spine_color_dark' => '#34D399',
                'height' => 'short',
                'thickness' => 'thin',
                'status' => 'finished',
                'favorite' => false,
                'progress' => 100.00,
                'started_date' => '2023-09-20 00:00:00',
                'finished_date' => '2023-10-15 00:00:00',
                'shelf_id' => $shelves->slice(2, 1)->first()->id,
                'position' => 1,
                'date_added' => '2023-09-10 00:00:00',
                'last_modified' => '2023-10-15 00:00:00',
                'purchase_date' => '2023-09-05 00:00:00',
                'purchase_price' => 16.99,
                'purchase_location' => 'Amazon',
            ],
            [
                'id' => Str::uuid()->toString(),
                'user_id' => $user->id,
                'title' => 'Deep Work',
                'author' => 'Cal Newport',
                'isbn' => '978-1455586691',
                'genre' => 'Productivity',
                'language' => 'English',
                'publisher' => 'Grand Central Publishing',
                'publish_year' => 2016,
                'pages' => 304,
                'format' => 'paperback',
                'spine_color_light' => '#1E3A8A',
                'spine_color_medium' => '#3B82F6',
                'spine_color_dark' => '#60A5FA',
                'height' => 'medium',
                'thickness' => 'regular',
                'status' => 'finished',
                'favorite' => false,
                'progress' => 100.00,
                'started_date' => '2023-08-25 00:00:00',
                'finished_date' => '2023-09-28 00:00:00',
                'shelf_id' => $shelves->slice(2, 1)->first()->id,
                'position' => 2,
                'date_added' => '2023-08-15 00:00:00',
                'last_modified' => '2023-09-28 00:00:00',
                'purchase_date' => '2023-08-10 00:00:00',
                'purchase_price' => 17.99,
                'purchase_location' => 'Bookstore',
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}